### ISSUE TITLE
Error : cannot find module joi 

### ISSUE THREAD

**Issue by GBeauny4D** [RobertHerhold/IcedFrisby#9]
Hi, 

i have installed icedFrisby in a package npm with xunit-file and mocha. 

The problem is that when i launch the test, the module joi which is installed in the module frisby cannot be found. 

Here my package dependencies : 

 "dependencies": {
    "icedfrisby": "^0.2.0",
    "mocha": "^2.2.5",
    "xunit-file": "0.0.6"
  } 

module.js:338
    throw err;
          ^
Error: Cannot find module 'joi'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

For information, i use a makeFile to launch test. 

test:
	@./node_modules/.bin/mocha -R xunit-file ./test/test.js
.PHONY: test

I use node version : v0.12.6. 

(I've this problem on a specific machine, it works well on another machine). 

Have you an idea about the issue? 

Thanks in advance,

**Comment by GBeauny4D** [comment]
In fact, it works after to install joi separately. Is it necessary?

**Comment by RobertHerhold** [comment]
You should just be able to run `npm install joi --save`, and it will add it to your list of dependencies in the `package.json` file. Hope it helps :)

**Comment by GBeauny4D** [comment]
Yes it works well :), but it's already installed with icedFrisby no? It cannot be re-used there? 
Why do i need to re-install it?

**Comment by RobertHerhold** [comment]
You are correct, it is in-fact included in IcedFrisby. Technically speaking, you *can* use IcedFrisby's version of Joi IF and you don't have it specified as a dependecy of your own in your own package.json and/or node_modules folder. Assuming you don't have your own copy, npm will install Joi as a dependency of IcedFrisby which you could use it in your code base with `var Joi = require('./node_modules/icedfrisby/node_modules/joi/lib/index.js')`.

Depending on IcedFrisby's version of Joi is really dirty though because if I or someone else updates IcedFrisby to use a newer version of Joi, your code could break if you updated IcedFrisby and you would have little hope of figuring out why your code is now broken.

If you install Joi yourself and it approximately matches the version IcedFrisby wants, it will not be installed twice.

I hope this helps!

As a side note, I will likely make Joi a peer dependency in the future to reduce risk of version mismatches. See http://blog.nodejs.org/2013/02/07/peer-dependencies/

**Comment by RobertHerhold** [comment]
Didn't mean to close. Please close as your leisure. :)

**Comment by GBeauny4D** [comment]
Thanks a lot Robert :)

**Comment by Bri4n-d3V** [comment]
> If you run `npm install joi --save`, it will add it to your list of dependencies in the `package.json` file. Hope it helps :)

I came from the future, 6 years later just to thank you for the answer. It worked!
